Parameters:
  ServiceName:
    Type: String
    Default: BananagramsService

Resources:
  Cluster:
    Type: AWS::ECS::Cluster

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Ref: ServiceName

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family:
        Ref: ServiceName
      RequiresCompatibilities:
        - FARGATE
      NetworkMode: awsvpc
      Memory: 512
      Cpu: 256
      ExecutionRoleArn:
        Fn::GetAtt: TaskDefinitionExecutionRole.Arn
      ContainerDefinitions:
        - Name:
            Ref: ServiceName
          Image:
            Fn::Sub: ${AWS::AccountId}.dkr.ecr.${AWS::Region}.${AWS::URLSuffix}/${ECRRepository}
          PortMappings:
            - ContainerPort: 3000
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group:
                Ref: ServiceName
              awslogs-region:
                Ref: AWS::Region
              awslogs-stream-prefix: Container

  TaskDefinitionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster:
        Ref: Cluster
      ServiceName:
        Ref: ServiceName
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - Ref: FargateContainerSecurityGroup
          Subnets:
            - Ref: PublicSubnetA
            - Ref: PublicSubnetB
      TaskDefinition:
        Ref: TaskDefinition
      LoadBalancers:
        - ContainerName:
            Ref: ServiceName
          ContainerPort: 3000
          TargetGroupArn:
            Ref: TargetGroup
