// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Players = __t.object("Players", {
  id: __t.u64(),
  userId: __t.identity(),
  roomId: __t.uuid(),
  username: __t.string(),
});
export type Players = __Infer<typeof Players>;

export const Rooms = __t.object("Rooms", {
  id: __t.uuid(),
  name: __t.string(),
});
export type Rooms = __Infer<typeof Rooms>;

